apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-frontend
  labels:
    app: guestbook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
        - name: guestbook
          image: proyectossd.azurecr.io/guestbook-frontend:${{ github.run_number }}
          ports:
            - containerPort: 80
          env:
            - name: REDIS_MASTER_SERVICE_HOST
              value: redis-master
            - name: REDIS_SLAVE_SERVICE_HOST
              value: redis-replica
