apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
      - name: guestbook
        image: proyectossd.azurecr.io/guestbook-frontend:latest
        ports:
        - containerPort: 80
